controller_manager:
  ros__parameters:
    update_rate: 500
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # lf_ft_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # rf_ft_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # lh_ft_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # rh_ft_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "base_imu"
    frame_id: "imu_link"

# lf_ft_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: "LF_ft"
#     frame_id: "LF_FOOT"

# rf_ft_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: "RF_ft"
#     frame_id: "RF_FOOT"

# lh_ft_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: "LH_ft"
#     frame_id: "LH_FOOT"

# rh_ft_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: "RH_ft"
#     frame_id: "RH_FOOT"
